### PR TITLE
Bump dependencies to fix npm audit vulnerabilities

### PR DESCRIPTION
**Pull request by kennsippell**
Bumping `xmlbuilder` and `async`.

Tests are passing after the code change to avoid the user of `#list`. Details at https://github.com/oozcitak/xmlbuilder-js/blob/master/CHANGELOG.md#400---2015-11-01

### CODE REVIEW

**Review by garethbowen — APPROVED** [review]
LGTM. Is it worth updating the other dependencies while you're in there?

**Comment by kennsippell** [comment]
Bit of a trade-off between risk of breaking things and unknown benefits of an upgrade. "If it ain't broke don't fix it"? I suspect new code has a higher chance of new vulnerabilities being discovered and putting us back here again...   Open to pushing the buttons if you think it's worthwhile.

**Comment by garethbowen** [comment]
I'll leave it up to you to decide!

**Comment by kennsippell** [comment]
Personally I'd leave as is. I can't merge in this repo though -- so you'll have to push the button :)

**Comment by garethbowen** [comment]
I've updated the permissions so you should be able to merge now!

**Pull request merged**
